Rai refactor
lemrey/sdk-nrf pull request #127
Opened 2023-11-15 10:47 UTC by MirkoCovizzi

2023-11-20 09:33 UTC, gregersrygg reviewed
We're not using RAI in ATv2 or our samples as far as I'm aware, so I'll leave it for others to approve.
The description doesn't say anything about the reason for this change. Is it an internal refactoring or a user improvement? The way this is written now, it will break  all customer applications that are using this feature. From what I can tell, there is already an abstraction layer in nrf91_sockets.c. If this is an internal refactoring, you can avoid breaking customer applications by keeping the old options on the user side, and translate to the new internal values in the abstraction layer.

2023-11-20 11:17 UTC, trantanen reviewed
I do share the comments made by @gregersrygg. I don't know how much RAI socket options are used by customers but breaking the API in this case seems to be at least a little questionable.

2023-11-20 11:17 UTC, trantanen commented on samples/cellular/modem_shell/src/sock/sock.c
>  		mosh_error("setsockopt() for %s failed with error %d", option_string, errno);
There is similar print four lines below.

```suggestion
		mosh_error("setsockopt() for SO_RAI with value %s failed with error %d", option_string, errno);
```

2023-11-22 06:32 UTC, MarkusLassila approved these changes
It is possible that we will implement a layer of abstraction to SLM to hide these socket changes from the end-user, before this will reach nrf main.
@tomi-font

2023-11-22 08:09 UTC, lemrey commented
We have deprecated things in libmodem before, but those were far more disruptive changes like whole headers (when moving away from socket-based APIs for AT, GNSS etc.) Yes, this is a breaking change - we could think of deprecating the old socket option and keeping it around for another 2 releases, but frankly it seems quite a minor change that takes very little adaptation to the code:
```
setsockopt(fd, SOL_SOCKET, SO_RAI_NO_DATA, NULL, 0);
setsockopt(fd, SOL_SOCKET, SO_RAI, RAI_NO_DATA, sizeof(int));
```
maybe in two places in an application? Given that this will be a chance to extend and improve the documentation of this feature as well, I would prefer removing the old socket option so that there is less confusion.

2023-11-22 08:36 UTC, trantanen commented
> but frankly it seems quite a minor change that takes very little adaptation to the code:
> 
> ```
> setsockopt(fd, SOL_SOCKET, SO_RAI_NO_DATA, NULL, 0);
> setsockopt(fd, SOL_SOCKET, SO_RAI, RAI_NO_DATA, sizeof(int));
> ```

I guess you need to have:
```
int rai_option = RAI_NO_DATA;
setsockopt(fd, SOL_SOCKET, SO_RAI, &rai_option, sizeof(int));
```

> We have deprecated things in libmodem before, but those were far more disruptive changes like whole headers (when moving away from socket-based APIs for AT, GNSS etc.)

Having done more disruptive changes earlier is not necessarily a good justification...

> maybe in two places in an application?

Yes, very little changes to adapt but that's not the main issue or a particularly good justification for breaking an API. Generally speaking, we do this for several APIs per release. If I were our customer, I wouldn't be too happy about this but that's the way we seem to operate with our APIs and maybe the customers are used to that.

> Given that this will be a chance to extend and improve the documentation of this feature as well, I would prefer removing the old socket option so that there is less confusion.

If we do these changes (which I guess we'll do anyway), I agree that we should rather remove than deprecate the old APIs.

2023-12-13 13:32 UTC, tomi-font requested changes

2023-12-13 13:32 UTC, tomi-font commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
> +    Ensure that you review and test your application to confirm that the new RAI configuration works as expected.
This seems like a good entry for the modem library.
For the SLM, we are concerned with the AT command interface only. The migration guide is for the end users, who only interact through the interface.

2023-12-13 13:56 UTC, MirkoCovizzi commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
> +    Ensure that you review and test your application to confirm that the new RAI configuration works as expected.
Thanks, updated

2023-12-14 07:12 UTC, tomi-font approved these changes
SLM looks good!

2023-12-14 14:09 UTC, eivindj-nordic commented on lib/nrf_modem_lib/nrf91_sockets.c
>  			break;
add deprecation to all:
```suggestion
			break;
			/* Deprecated */
```

2023-12-15 09:50 UTC, MirkoCovizzi commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
> +    Ensure that you review and test your application to confirm that the new RAI configuration works as expected.
Removed

2023-12-15 09:53 UTC, MirkoCovizzi commented on lib/nrf_modem_lib/nrf91_sockets.c
>  			break;
Thank you for the feedback, I reworded it.

2023-12-18 07:46 UTC, tokangas commented on samples/cellular/modem_shell/src/sock/sock_shell.c
> +	"      --rai_last,           Sets SO_RAI option with value NRF_RAI_LAST.\n"
```suggestion
	"      --rai_last,           Sets SO_RAI option with value RAI_LAST.\n"
```

2023-12-18 07:46 UTC, tokangas commented on samples/cellular/modem_shell/src/sock/sock_shell.c
> +	"      --rai_no_data,        Sets SO_RAI option with value NRF_RAI_NO_DATA.\n"
```suggestion
	"      --rai_no_data,        Sets SO_RAI option with value RAI_NO_DATA.\n"
```

2023-12-18 07:46 UTC, tokangas commented on samples/cellular/modem_shell/src/sock/sock_shell.c
> +	"      --rai_one_resp,       Sets SO_RAI option with value NRF_RAI_ONE_RESP.\n"
```suggestion
	"      --rai_one_resp,       Sets SO_RAI option with value RAI_ONE_RESP.\n"
```

2023-12-18 07:46 UTC, tokangas commented on samples/cellular/modem_shell/src/sock/sock_shell.c
> +	"      --rai_ongoing,        Sets SO_RAI option with value NRF_RAI_ONGOING.\n"
```suggestion
	"      --rai_ongoing,        Sets SO_RAI option with value RAI_ONGOING.\n"
```

2023-12-18 07:46 UTC, tokangas commented on samples/cellular/modem_shell/src/sock/sock_shell.c
> +	"      --rai_wait_more,      Sets SO_RAI option with value NRF_RAI_WAIT_MORE.\n"
```suggestion
	"      --rai_wait_more,      Sets SO_RAI option with value RAI_WAIT_MORE.\n"
```

2023-12-18 09:08 UTC, MirkoCovizzi commented on samples/cellular/modem_shell/src/sock/sock_shell.c
> +	"      --rai_last,           Sets SO_RAI option with value NRF_RAI_LAST.\n"
Updated

2023-12-18 10:13 UTC, tokangas approved these changes

2023-12-18 10:52 UTC, eivindj-nordic approved these changes

2023-12-21 10:30 UTC, umapraseeda commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * The :c:macro:`SO_RAI` socket option for Release Assistance Indication (RAI). This socket option substitutes the deprecated :c:macro:`SO_RAI_*` socket options. To specify the indication, use the
```suggestion
    * The :c:macro:`SO_RAI` socket option for Release Assistance Indication (RAI).
      This socket option substitutes the deprecated :c:macro:`SO_RAI_*` socket options.
      To specify the indication, use the :c:macro:`RAI_*` values.
```

2023-12-21 10:30 UTC, umapraseeda commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * The :c:macro:`SO_RAI_WAIT_MORE` socket option is deprecated. Use the :c:macro:`SO_RAI` socket option instead.
```suggestion
    * The following socket options have been deprecated:
         
       * :c:macro:`SO_RAI_NO_DATA` 
       * :c:macro:`SO_RAI_LAST`
       * :c:macro:`SO_RAI_ONE_RESP`
       * :c:macro:`SO_RAI_ONGOING`
       * :c:macro:`SO_RAI_WAIT_MORE`
     
      Use the :c:macro:`SO_RAI` socket option instead.
```

2023-12-21 10:30 UTC, umapraseeda commented on applications/serial_lte_modem/doc/SOCKET_AT_commands.rst
> +      * ``2`` - :c:macro:`RAI_LAST`: Indicate that the application does not intend to send more data after the next call to send() or sendto(). This lets the modem exit connected mode more quickly af
```suggestion
      * ``2`` - :c:macro:`RAI_LAST`.
        Indicates that the application does not intend to send more data after the next call to ``send()`` or ``sendto()``.
        This lets the modem exit connected mode more quickly after sending the data.
```

2023-12-21 10:30 UTC, umapraseeda commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
> +  * The handling of Release Assistance Indication (RAI) socket options has been updated in the ``#XSOCKETOPT`` command. The individual RAI-related socket options have been consolidated into a single
```suggestion
  * The handling of Release Assistance Indication (RAI) socket options has been updated in the ``#XSOCKETOPT`` command.
    The individual RAI-related socket options have been consolidated into a single ``SO_RAI`` option.
    You must modify your application to use the new ``SO_RAI`` option with the corresponding value to specify the RAI behavior.
```

2023-12-21 10:30 UTC, umapraseeda commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
> +  * The Release Assistance Indication (RAI) socket options have been deprecated and replaced with a new consolidated socket option. If your application uses the old RAI socket options, you need to up
```suggestion
  * The Release Assistance Indication (RAI) socket options have been deprecated and replaced with a new consolidated socket option.
    If your application uses the old RAI socket options, you need to update your socket configuration as follows:
```

2023-12-21 10:30 UTC, umapraseeda commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
> +    * If you previously used ``AT#XSOCKETOPT=1,54,`` replace it with ``AT#XSOCKETOPT=1,61,5`` to indicate RAI_WAIT_MORE.
```suggestion
    * If you previously used ``AT#XSOCKETOPT=1,50,`` replace it with ``AT#XSOCKETOPT=1,61,1`` to indicate ``RAI_NO_DATA``.
    * If you previously used ``AT#XSOCKETOPT=1,51,`` replace it with ``AT#XSOCKETOPT=1,61,2`` to indicate ``RAI_LAST``.
    * If you previously used ``AT#XSOCKETOPT=1,52,`` replace it with ``AT#XSOCKETOPT=1,61,3`` to indicate ``RAI_ONE_RESP``.
    * If you previously used ``AT#XSOCKETOPT=1,53,`` replace it with ``AT#XSOCKETOPT=1,61,4`` to indicate ``RAI_ONGOING``.
    * If you previously used ``AT#XSOCKETOPT=1,54,`` replace it with ``AT#XSOCKETOPT=1,61,5`` to indicate ``RAI_WAIT_MORE``.
```

2023-12-21 10:30 UTC, umapraseeda commented on applications/serial_lte_modem/doc/SOCKET_AT_commands.rst
> +      * ``3`` - :c:macro:`RAI_ONE_RESP`: Indicate that the application is expecting to receive just one data packet after the next call to send() or sendto(). This lets the modem exit connected mode
```suggestion
      * ``3`` - :c:macro:`RAI_ONE_RESP`.
        Indicates that the application is expecting to receive just one data packet after the next call to ``send()`` or ``sendto()``.
        This lets the modem exit connected mode more quickly after having received the data.
```

2023-12-21 10:30 UTC, umapraseeda commented on applications/serial_lte_modem/doc/SOCKET_AT_commands.rst
> +      * ``4`` - :c:macro:`RAI_ONGOING`: Indicate that the application is expecting to receive just one data packet after the next call to send() or sendto(). This lets the modem exit connected mode m
```suggestion
      * ``4`` - :c:macro:`RAI_ONGOING`.
        Indicates that the application is expecting to receive just one data packet after the next call to ``send()`` or ``sendto()``.
        This lets the modem exit connected mode more quickly after having received the data.
```

2023-12-21 10:30 UTC, umapraseeda commented on applications/serial_lte_modem/doc/SOCKET_AT_commands.rst
> +      * ``5`` - :c:macro:`RAI_WAIT_MORE`: Indicate that the socket is in active use by a server application. This lets the modem stay in connected mode longer.
```suggestion
      * ``5`` - :c:macro:`RAI_WAIT_MORE`.
        Indicates that the socket is in active use by a server application.
        This lets the modem stay in connected mode longer.
```

2024-01-03 09:37 UTC, umapraseeda approved these changes

2024-01-03 09:37 UTC, umapraseeda commented on applications/serial_lte_modem/doc/SOCKET_AT_commands.rst
> +        Indicates that the application does not intend to send more data after the next call to send() or sendto().
```suggestion
        Indicates that the application does not intend to send more data after the next call to :c:func:`send` or :c:func:`sendto`.
```

2024-01-03 09:37 UTC, umapraseeda commented on applications/serial_lte_modem/doc/SOCKET_AT_commands.rst
> +        Indicates that the application is expecting to receive just one data packet after the next call to send() or sendto().
```suggestion
        Indicates that the application is expecting to receive just one data packet after the next call to :c:func:`send` or :c:func:`sendto`.
```

2024-01-03 09:37 UTC, umapraseeda commented on applications/serial_lte_modem/doc/SOCKET_AT_commands.rst
> +        Indicates that the application is expecting to receive just one data packet after the next call to send() or sendto().
```suggestion
        Indicates that the application is expecting to receive just one data packet after the next call to :c:func:`send` or :c:func:`sendto`.
```

2024-01-05 10:23 UTC, lemrey commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
> +    If your application uses the old RAI socket options, you need to update your socket configuration as follows:
Perhaps, I would say "If you application uses the ~old~ RAI socket options", since the upcoming NCS version (v2.6.0) introduces the new options for the first time and the distinction between new/old did not exist before.
So if the customer was using the  RAI socket options before, then they must migrate to the new ones.

2024-01-05 10:24 UTC, lemrey approved these changes
Left a minor comment, otherwise looks very good!

2024-01-10 15:16 UTC, MirkoCovizzi commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
> +    If your application uses the old RAI socket options, you need to update your socket configuration as follows:
How about `if your application uses the dprecated RAI socket options` instead?

2024-01-11 11:27 UTC, lemrey commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * The :c:macro:`SO_RAI_WAIT_MORE` socket option is deprecated. Use the :c:macro:`SO_RAI` socket option instead.
@MirkoCovizzi 👆🏻

2024-01-15 12:11 UTC, umapraseeda approved these changes

2024-01-17 13:58 UTC, lemrey approved these changes
Good job

2024-01-17 13:58 UTC, merged