libmodem: Call the trace processed callback function after sending trace over uart/rtt
lemrey/sdk-nrf pull request #42
Opened 2021-10-29 12:28 UTC by balaji-nordic

Modified nrf_modem_os_trace_put function to call the
nrf_modem_trace_processed_callback as soon as the uart tx or rtt tx
function returns.
Smoke testing of traces done using UART transport.

Signed-off-by: Balaji Srinivasan <balaji.srinivasan@nordicsemi.no>

2021-11-08 12:05 UTC, eivindj-nordic commented
@balaji-nordic I get "undefined reference to 'nrf_modem_trace_processed_callback'" when building with libmodem master and `CONFIG_ASSERT=y`. Where is this callback defined?

2021-11-08 12:22 UTC, eivindj-nordic requested changes

2021-11-08 12:22 UTC, eivindj-nordic commented on lib/nrf_modem_lib/nrf_modem_os.c
> +		__ASSERT(nrf_modem_trace_processed_callback(data, len) == 0,
Should `nrf_modem_trace_processed_callback` be called only if `CONFIG_ASSERT=y`?

2021-11-08 12:22 UTC, eivindj-nordic commented on lib/nrf_modem_lib/nrf_modem_os.c
> +	__ASSERT(nrf_modem_trace_processed_callback(data, len) == 0,
Same as above

2021-11-08 15:20 UTC, balaji-nordic commented on lib/nrf_modem_lib/nrf_modem_os.c
> +		__ASSERT(nrf_modem_trace_processed_callback(data, len) == 0,
No. It should be called no matter what. I will fix this. I was not aware of the  CONFIG_ASSERT behaviour

2021-11-15 14:52 UTC, eivindj-nordic commented on lib/nrf_modem_lib/nrf_modem_os.c
> +		__ASSERT(err == 0, "nrf_modem_trace_processed_callback returns error");
Maybe also add a `(void) err;` etc. to avoid this throwing an `warning: unused variable 'err'` when building without assert?

2021-12-02 14:34 UTC, lemrey commented on lib/nrf_modem_lib/nrf_modem_os.c
> +		__ASSERT(err == 0, "nrf_modem_trace_processed_callback returns error");
@balaji-nordic could you address this comment?
I would move `err` at the beginning of the function and `(void)err;` immediately afterwards.

2021-12-07 10:06 UTC, balaji-nordic commented on lib/nrf_modem_lib/nrf_modem_os.c
> +		__ASSERT(err == 0, "nrf_modem_trace_processed_callback returns error");
sorry I missed to see this comment. Will fix now.

2021-12-07 10:23 UTC, balaji-nordic commented on lib/nrf_modem_lib/nrf_modem_os.c
> +		__ASSERT(err == 0, "nrf_modem_trace_processed_callback returns error");
Actually I dont get the warning when building without asserts. Thats because the variable gets assigned to anyway even if asserts are disabled. So I will only move the declaration to the top.

2021-12-07 14:50 UTC, lemrey commented
@eivindj-nordic please have a look again

2021-12-07 15:08 UTC, eivindj-nordic approved these changes

2021-12-09 11:33 UTC, lemrey commented
Have rebased this, needed after #216

2021-12-09 14:21 UTC, merged